name: Your New Jekyll Site
markdown: redcarpet
highlighter: 'pygments'
exclude:
  - "node_modules"
  - "package.json"
  - "Rakefile"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "config.rb"
  - "uncss.js"
