// Generated by CoffeeScript 1.6.3
"use strict";
var StyleJS;

String.prototype.capitalize = function() {
  return this.substr(0, 1).toUpperCase() + this.substr(1);
};

String.prototype.toJSProperty = function() {
  var js_prop;
  js_prop = this.split('-').map(function(e) {
    return e.capitalize();
  }).join('');
  return js_prop.substr(0, 1).toLowerCase() + js_prop.substr(1);
};

StyleJS = (function() {
  StyleJS.prototype.element = null;

  StyleJS.prototype.items = [];

  function StyleJS(config) {
    var elements, input, item, property, _i, _j, _len, _len1, _ref, _ref1;
    this.config = config;
    this.element = document.createElement("div");
    _ref = this.config.items;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      elements = document.body.querySelectorAll(item.selectors);
      _ref1 = item.properties;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        property = _ref1[_j];
        input = document.createElement('input');
        input.setAttribute('type', property.type);
        input.setAttribute('data-property', property.name);
        input.value = property.initial;
        input.onchange = function() {
          var element, targAttr, _k, _len2, _results;
          _results = [];
          for (_k = 0, _len2 = elements.length; _k < _len2; _k++) {
            element = elements[_k];
            targAttr = this.getAttribute("data-property");
            targAttr = targAttr.toJSProperty();
            _results.push(element.style[targAttr] = this.value);
          }
          return _results;
        };
        input.onkeyup = input.onchange;
        this.element.appendChild(input);
      }
    }
    document.body.appendChild(this.element);
  }

  StyleJS.prototype.showIn = function(selector) {};

  StyleJS.prototype.hide = function() {
    return alert("Not Implemented");
  };

  StyleJS.prototype.show = function() {
    return alert("Not Implemented");
  };

  return StyleJS;

})();

window.StyleJS = StyleJS;
